using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Threading.Tasks;

using Engine.Extensions;
using Engine.Interfaces;

namespace Engine.Workflows;

public sealed class AddJobWorkflow(
    AppWorkspace context,
    IEnumerable<IWorkflowWorker> workers) : BaseWorkflow(context, workers)
{
    public override string WorkflowName => Commands.AddJob;

    protected override async Task ExecuteWorkflowAsync(string[] args)
    {
        string[] filteredArgs = [.. args.Where(arg => arg != WorkflowName)];
        string? name = filteredArgs.FirstOrDefault(arg => !arg.StartsWith('-'));
        if (string.IsNullOrWhiteSpace(name))
        {
            throw new ArgumentException($"Usage: {App.Name} {Commands.AddJob} <name> [--project <project>]");
        }

        string? schedule = ParseOptionValue(filteredArgs, "--schedule");
        if (!string.IsNullOrWhiteSpace(schedule))
        {
            schedule = schedule.Trim();
            ValidateSchedule(schedule);
        }

        string? description = NormalizeOptionalString(ParseOptionValue(filteredArgs, "--description"));
        string? priority = NormalizeOptionalString(ParseOptionValue(filteredArgs, "--priority"));
        if (priority is not null)
        {
            ValidatePriority(priority);
        }

        string jobDir = Context.BackendPath.Combine("jobs").Combine(name);
        if (jobDir.Exists())
        {
            throw new InvalidOperationException($"Job '{name}' already exists.");
        }

        Directory.CreateDirectory(jobDir);
        string filePath = Path.Combine(jobDir, $"{Files.Index}{FileExtensions.Ts}");
        await File.WriteAllTextAsync(filePath, BuildJobTemplate(name));

        UpdatePackageJsonWithJob(name, schedule, description, priority);
        Console.WriteLine($"Created backend job at {Path.GetRelativePath(Context.WorkingPath, filePath)} and updated package.json manifest.");
    }

    private static string BuildJobTemplate(string name)
    {
        return $$"""
// Generated by webstir add-job
export async function run(): Promise<void> {
  console.info('[job:{name}] ran at', new Date().toISOString());
}

const isMain = (() => {
  try {
    const argv1 = process.argv?.[1];
    if (!argv1) return false;
    const here = new URL(import.meta.url);
    const run = new URL(`file://${argv1}`);
    return here.pathname === run.pathname;
  } catch {
    return false;
  }
})();

if (isMain) {
  run().catch((err) => {
    console.error(err);
    process.exitCode = 1;
  });
}
""";
    }

    private void UpdatePackageJsonWithJob(string name, string? schedule, string? description, string? priority)
    {
        string packageJsonPath = Path.Combine(Context.WorkingPath, Files.PackageJson);
        if (!File.Exists(packageJsonPath))
        {
            throw new FileNotFoundException($"{Files.PackageJson} not found in workspace root.", packageJsonPath);
        }

        JsonNode root = JsonNode.Parse(File.ReadAllText(packageJsonPath)) ?? new JsonObject();
        JsonObject pkg = root as JsonObject ?? new JsonObject();
        JsonObject webstir = pkg["webstir"] as JsonObject ?? new JsonObject();
        JsonObject moduleManifest = webstir["moduleManifest"] as JsonObject ?? new JsonObject();
        JsonArray jobs = moduleManifest["jobs"] as JsonArray ?? new JsonArray();

        JsonObject? jobObject = jobs
            .Select(j => j as JsonObject)
            .FirstOrDefault(o => o is not null && string.Equals((string?)o["name"], name, StringComparison.Ordinal));

        if (jobObject is null)
        {
            jobObject = new JsonObject();
            jobs.Add(jobObject);
        }

        jobObject["name"] = name;
        ApplyOptionalString(jobObject, "schedule", schedule);
        ApplyOptionalString(jobObject, "description", description);
        ApplyPriority(jobObject, priority);

        moduleManifest["jobs"] = jobs;
        webstir["moduleManifest"] = moduleManifest;
        pkg["webstir"] = webstir;

        JsonSerializerOptions options = new()
        {
            WriteIndented = true
        };
        File.WriteAllText(packageJsonPath, pkg.ToJsonString(options));
    }

    private static string? ParseOptionValue(string[] args, string option)
    {
        for (int i = 0; i < args.Length; i++)
        {
            string arg = args[i];
            if (string.Equals(arg, option, StringComparison.OrdinalIgnoreCase))
            {
                if (i + 1 < args.Length && !args[i + 1].StartsWith('-'))
                {
                    return args[i + 1];
                }
                return null;
            }

            if (arg.StartsWith(option + "=", StringComparison.OrdinalIgnoreCase))
            {
                return arg[(option.Length + 1)..];
            }
        }

        return null;
    }

    private static string? NormalizeOptionalString(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return null;
        }

        return value.Trim();
    }

    private static void ApplyOptionalString(JsonObject target, string property, string? value)
    {
        if (!string.IsNullOrEmpty(value))
        {
            target[property] = value;
        }
        else
        {
            target.Remove(property);
        }
    }

    private static void ApplyPriority(JsonObject target, string? priority)
    {
        if (string.IsNullOrEmpty(priority))
        {
            target.Remove("priority");
            return;
        }

        if (int.TryParse(priority, NumberStyles.Integer, CultureInfo.InvariantCulture, out int numeric))
        {
            target["priority"] = numeric;
            return;
        }

        target["priority"] = priority;
    }

    private static void ValidatePriority(string priority)
    {
        if (priority.Length == 0)
        {
            throw new ArgumentException("--priority value cannot be empty or whitespace.");
        }

        if (int.TryParse(priority, NumberStyles.Integer, CultureInfo.InvariantCulture, out _))
        {
            return;
        }

        // Non-numeric priorities are allowed as free-form strings.
    }

    private static void ValidateSchedule(string schedule)
    {
        string trimmed = schedule.Trim();
        if (trimmed.Length == 0)
        {
            throw new ArgumentException("--schedule value cannot be empty or whitespace.");
        }

        if (trimmed.StartsWith("@", StringComparison.Ordinal))
        {
            string macro = trimmed[1..];
            if (!AllowedScheduleMacros.Contains(macro, StringComparer.OrdinalIgnoreCase))
            {
                string macros = string.Join(", ", AllowedScheduleMacros);
                throw new ArgumentException($"Invalid --schedule value '{schedule}'. Allowed macros: @{macros}.");
            }
            return;
        }

        string[] parts = trimmed.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length is < 5 or > 7)
        {
            throw new ArgumentException($"Invalid --schedule value '{schedule}'. Expected 5-7 space-separated fields or @macro.");
        }

        foreach (string part in parts)
        {
            if (!IsValidCronField(part))
            {
                throw new ArgumentException($"Invalid cron field '{part}' in --schedule value '{schedule}'.");
            }
        }
    }

    private static bool IsValidCronField(string field)
    {
        foreach (char c in field)
        {
            if (char.IsLetterOrDigit(c))
            {
                continue;
            }

            if (c is '*' or '/' or ',' or '-' or '?' or '#' or 'L' or 'W' or 'C')
            {
                continue;
            }

            return false;
        }

        return true;
    }

    private static readonly string[] AllowedScheduleMacros =
    {
        "yearly",
        "annually",
        "monthly",
        "weekly",
        "daily",
        "midnight",
        "hourly",
        "reboot"
    };
}
