storage: /verdaccio/storage
plugins: /verdaccio/plugins
listen: 0.0.0.0:4873

web:
  enable: true
  title: Verdaccio

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
    algorithm: bcrypt

packages:
  '@*/*':
    access: $all
    publish: $all
    proxy: npmjs
  '**':
    access: $all
    publish: $all
    proxy: npmjs

middlewares:
  audit:
    enabled: true

log:
  type: stdout
  format: pretty
  level: http
